#!/usr/bin/env bash
# configure redirect me to trading view
sudo apt update

sudo apt install -y nginx

echo 'server {
    listen 80;
    server_name 289867-web-01;

    location /redirect_me {
        return 301 https://www.tradingview.com/;
    }
}' | sudo tee /etc/nginx/sites-available/redirect

sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

if sudo nginx -t; then
    sudo service nginx reload
else
    exit 1
fi
