#!/usr/bin/env bash

sudo apt update

if ! dpkg -l | grep -q "nginx"; then
    sudo apt install -y nginx
fi

echo 'server {
    listen 80;
    server_name 289867-web-01;

    location /redirect_me {
        return 301 https://www.tradingview.com/;
    }
}' | sudo tee /etc/nginx/sites-available/redirect

sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

if [ -f /etc/nginx/sites-enabled/default ]; then
    sudo rm /etc/nginx/sites-enabled/default
fi

if sudo nginx -t; then
    sudo service nginx reload
else
    exit 1
fi
