#!/usr/bin/env bash
# configires a custom http head tto the server
sudo apt update

# Install Nginx if it's not already installed
if ! dpkg -l | grep -q "nginx"; then
    sudo apt install -y nginx
fi

HOSTNAME=$(hostname);
echo 'server {
    listen 80;
    server_name '"$HOSTNAME"';

    add_header X-Served-By $HOSTNAME;
    location / {
        add_header X-Served-By $HOSTNAME;
        # Additional server configurations go here, if needed.
    }
}' | sudo tee /etc/nginx/sites-available/custom_header

sudo ln -sf /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

if sudo nginx -t; then
    sudo service nginx reload
else
    exit 1
fi
