#!/usr/bin/env bash
# check arg count
if [ "$#" -ne 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi
# assign variables
F_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"
# execute command
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$F_PATH" "$USERNAME@$IP:~/"
