#!/usr/bin/env bash
# fixes port 80 listening bug
#remove the existing link
rm /etc/nginx/sites-enabled/default
# create a new link and reconfigure port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart engine
sudo service nginx restart
