#!/usr/bin/env bash
# this script is explained by each coode snippet for better understanding
# Function to handle SIGTERM and SIGQUIT signals
handle_term_quit()
{
    echo "Deleting PID file and terminating."
    rm /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
handle_int()
{
    echo "Y U no love me?!"
    exit 0
}

# Function to handle SIGTERM signal
handle_term()
{
    echo "I hate the kill command"
    exit 0
}

# Register the signal handlers
trap handle_term_quit SIGTERM SIGQUIT
trap handle_int SIGINT
trap handle_term SIGTERM

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
