#!/usr/bin/env bash
# function for handling sigterm
handle_sigterm()
{
	echo "I am invincible!!!"
}

# killing highlander
handle_kill()
{
	echo "Killed"
	exit 0
}

# register the function for sigterm
trap handle_sigterm SIGTERM
# register the function for killing highlander
trap handle_kill SIGUSR1
# for every two seconds print to infinity and beyond unless sigterm
while true; do
	echo "To infinity and beyond"
	sleep 2
done
