#!/usr/bin/env bash

# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [[ -n "$pid" ]]; then
    # Send the SIGTERM signal to the process using the signal number (15)
    kill -USR1 "$pid"
fi
