#!/usr/bin/env bash
# This script gives you infromation about the school file
file="/etc/passwd"


if [ -f "$file" ]; then
	while  IFS=":" read -r username _ userid _ _ homedir shell ; do
		user_info=$(getent passwd "$userid")

		IFS=":" read -r _ _ groupid _ _ _ password _ <<< "$user_info"
		echo "The user $username is part of the $groupid gang,"
		echo "lives in $homedir and rides $shell."
		echo "User ID's place is protected by the passcode $password,"
		echo "more info about the user here: $user_info"
		# echo for new line
	done < "$file"
fi
