#!/usr/bin/env bash
# This script displays visitor IP along with HTTP status code from the Apache log file

log="apache-access.log"

if [ ! -f "$log" ]; then
	echo "The file $log does not exist"
	exit 1
fi
awk '{print $1, $9}' "$log"
