#!/usr/bin/env bash
# This script is displaying "Best School" for all iterations bad luck on the 4th and good luck on the 8th
i=0

while [ "$i" -le 10 ]; do
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
