#!/usr/bin/env bash
# This script is a mini representation of a 12 hour clock

hour=0
min=0

while [ "$hour" -le 12 ]; do
	echo "Hour: $hour"
	while [ "$min" -le 59 ]; do
		echo "$min"
		((min++))
	done
	((hour++))
	min=1
done
