#!/usr/bin/env bash
# changes the user thats runnig the whoami command
# Check if an argument was provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Store the provided username in a variable
username="$1"

# Run the 'whoami' command as the specified user
sudo -u "$username" whoami
