#!/usr/bin/env bash

# Set the SSH private key file and server address
private_key_file="$HOME/.ssh/school"
server_address="8.8.8.8"
ssh_user="ubuntu"

# Connect to the server using SSH
ssh -i "$private_key_file" "$ssh_user@$server_address"
