#!/usr/bin/env bash

# Set the SSH private key file and server address
private_key_file="$HOME/.ssh/id_rsa"
server_address="54.236.46.23"
ssh_user="ubuntu"

ssh -i "$private_key_file" "$ssh_user@$server_address"
